[package]
authors = ["Matt Ickstadt <mattico8@gmail.com>"]
name = "hydration-bot"
version = "0.1.0"

[dependencies]
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"

[dependencies.serenity]
path = "../serenity"
features = ["cache", "framework", "standard_framework"]